-- First, let's only add the restaurants that don't already exist
INSERT INTO public.restaurants (name, description, address, city, country, phone, email, website, lat, lng, status) 
SELECT name, description, address, city, country, phone, email, website, lat, lng, status
FROM (VALUES 
  ('An Nam', 'En middag på An Nam er som en reise gjennom Vietnam, fra rismarkene i nord til havnene i sør. Østens krydder og urter kombineres med kortreiste, norske råvarer.', 'Pedersgata, Stavanger', 'Stavanger', 'Norway', '+47 51 89 44 48', 'post@annamstavanger.no', 'https://annamstavanger.no', 58.9700, 5.7331, 'active'),
  ('Bravo', 'Á la carte meny med enkle småretter og snacks. Råvarene er kortreiste og varieres etter sesong. Vinliste med naturviner. Omtalt i Michelin Guide. Overkommelig pris.', 'Pedersgata, Stavanger', 'Stavanger', 'Norway', '+47 51 84 38 40', 'post@bravostavanger.no', 'https://bravostavanger.no', 58.9700, 5.7331, 'active'),
  ('Bellies', 'Restauranten bruker utelukkende ingredienser fra planteriket og komponerer fantastiske retter som tilfredsstiller både øyet og ganen. Spisestedet er anbefalt i Michelin Guide.', 'Pedersgata, Stavanger', 'Stavanger', 'Norway', '+47 51 84 38 40', 'post@belliesstavanger.no', 'https://belliesstavanger.no', 58.9700, 5.7331, 'active'),
  ('Restaurant Broken', 'Med spesialisering på moderne norsk mat, fisk, sjømat og vegansk mat setter kokk og innehaver Alan Kaye sin ære i å tilby en raffinert kulinarisk opplevelse hvor hver rett er laget fra bunnen av med de ferskeste ingredienser.', 'Langgata 9, Stavanger', 'Stavanger', 'Norway', '+47 400 00 000', 'post@restaurantbroken.no', 'https://restaurantbroken.no', 58.9700, 5.7331, 'active'),
  ('Casa Gio', 'Hos Casa Gio serveres det mat laget av kvalitetsråvarer, og med få kombinasjoner. Fersk pasta, myk ravioli, rykende varm tagliatelle, risotto og alt det gode man forbinder med det italienske kjøkken.', 'Pedersgata, Stavanger', 'Stavanger', 'Norway', '+47 51 89 44 44', 'post@casagio.no', 'https://casagio.no', 58.9700, 5.7331, 'active'),
  ('Delicatessen Tapasbar', 'Hos Delicatessen kan du senke skuldrene og nyte et glass vin og spise deilige tapas av mange ulike slag. Her finner alle noe de liker å spise og maten er som skapt for å deles i hyggelig lag enten du sitter rundt et bord eller nyter den til et glass vin i baren.', 'Pedersgata, Stavanger', 'Stavanger', 'Norway', '+47 51 89 44 45', 'post@delicatessentapasbar.no', 'https://delicatessentapasbar.no', 58.9700, 5.7331, 'active'),
  ('Hekkan Burger', 'Byenst beste burgere lages for hånd på huset, av det aller beste kjøttet fra Prima Jæren, og grilles deretter på biologisk trekull. Severes med godt, lokalprodusert brioche-brød.', 'Pedersgata, Stavanger', 'Stavanger', 'Norway', '+47 51 89 44 46', 'post@hekkanburger.no', 'https://hekkanburger.no', 58.9700, 5.7331, 'active'),
  ('Istanbul Pizza & Kebab', 'Istanbul byr på Tradisjonelle tyrkiske retter og take away. Forrykende god kebab, falafel og linsesuppe og et variert utvalg pizza, og alltid nybakte pitabrød.', 'Pedersgata, Stavanger', 'Stavanger', 'Norway', '+47 51 89 44 47', 'post@istanbulpizza.no', 'https://istanbulpizza.no', 58.9700, 5.7331, 'active'),
  ('Kansui', 'Kansui restaurant serverer byens beste japan-style ramen! Flere varianter på menyen. Her kan du spise som en japaner og nyte måltidet i lange slurp!', 'Pedersgata, Stavanger', 'Stavanger', 'Norway', '+47 51 89 44 48', 'post@kansui.no', 'https://kansui.no', 58.9700, 5.7331, 'active'),
  ('Restaurant K2', 'Restauranten har fokus på å jobbe så økologisk, lokalt og bærekraftig som mulig, i alle ledd, og spisestedet har blitt belønnet med både Michelin-stjerne og bærekraftskløver.', 'Pedersgata, Stavanger', 'Stavanger', 'Norway', '+47 51 84 37 40', 'post@restaurantk2.no', 'https://restaurantk2.no', 58.9700, 5.7331, 'active'),
  ('Meze Restaurant', 'Middagsretter og småretter fra Middelhavslandene som serveres alene eller sammen til et helhetlig måltid. Meze er perfekt å dele med venner!', 'Pedersgata, Stavanger', 'Stavanger', 'Norway', '+47 51 89 44 49', 'post@mezerestaurant.no', 'https://mezerestaurant.no', 58.9700, 5.7331, 'active'),
  ('Miyako', 'Asian fusion konsept inspirert av flere østlige, asiatiske land. Et bredt utvalg av sushi, sashimi, tempura og varmretter, samt et utvalg vegetar- og veganske retter.', 'Pedersgata, Stavanger', 'Stavanger', 'Norway', '+47 51 89 44 50', 'post@miyako.no', 'https://miyako.no', 58.9700, 5.7331, 'active'),
  ('Molinå Bakery & Eatery', 'Molinå er et surdeigsbakeri, spiseri og kafè i Verksgata 17 i Stavanger. De bruker lokale og økologiske ingredienser, og lager produkter som er bærekraftige for miljøet.', 'Verksgata 17, Stavanger', 'Stavanger', 'Norway', '+47 51 89 44 51', 'post@molina.no', 'https://molina.no', 58.9700, 5.7331, 'active'),
  ('Noras Kitchen', 'Pakistansk/indisk familierestaurant som kombinerer tradisjonsrike oppskrifter med det moderne. Alle måltider er Halal-vennlige. Spis inne, take away og catering.', 'Pedersgata, Stavanger', 'Stavanger', 'Norway', '+47 51 89 44 52', 'post@noraskitchen.no', 'https://noraskitchen.no', 58.9700, 5.7331, 'active'),
  ('Panzanella Pizzeria', 'Drømmer du om ekte italiensk pizza? Da er Panzanella Pizzeraia stedet du bør oppsøke! Her lager de pizza av aller høyeste kvalitet, med de beste råvarer i både bunner og toppinger.', 'Pedersgata, Stavanger', 'Stavanger', 'Norway', '+47 51 89 44 53', 'post@panzanella.no', 'https://panzanella.no', 58.9700, 5.7331, 'active'),
  ('Sabi Omakase', 'Jubelen stod i taket i 2017 da sushi-kokken Roger Asakil Joya hos Sabi Omakase fikk en stjerne i den prestisjefylte Michelin Guide. Stjernen er fremdeles i god behold.', 'Pedersgata, Stavanger', 'Stavanger', 'Norway', '+47 51 89 44 54', 'post@sabiomakase.no', 'https://sabiomakase.no', 58.9700, 5.7331, 'active'),
  ('Yips Dumplings & Digg', 'Her får du servert et bredt utvalg av fra det asiatiske kjøkken. Yips Dumplings & Digg benytter lokale og kortreiste råvarer til å lage spennende og smakfulle retter.', 'Pedersgata, Stavanger', 'Stavanger', 'Norway', '+47 51 89 44 55', 'post@yips.no', 'https://yips.no', 58.9700, 5.7331, 'active'),
  ('Zouq', 'Hos Zouq får du nydelige retter basert på tradisjonsrike pakistanske oppskrifter. Spis inne, take away og catering', 'Pedersgata, Stavanger', 'Stavanger', 'Norway', '+47 51 89 44 56', 'post@zouq.no', 'https://zouq.no', 58.9700, 5.7331, 'active')
) AS new_restaurants(name, description, address, city, country, phone, email, website, lat, lng, status)
WHERE NOT EXISTS (
  SELECT 1 FROM public.restaurants WHERE restaurants.name = new_restaurants.name
);